### ISSUE TITLE
what bout lwjgl 2

### ISSUE THREAD

**Issue by Jerem584** [ice1000/jimgui#45] opened 2019-08-17 09:58 UTC
os: windows 10 1803 
ide: eclipse
lwjgl 2.9.1

Hi

so, how can i try or get the windows pointer with this version of lwjgl 2?
We can't get glfw with this version of lwjgl, and am trying to just inject this to minecraft

also i created a dll that can inject imgui then display directly in the windows, i could send src if they can help you...
 

Cordially, Theo

**Comment by ice1000** [comment] 2019-08-17 18:45
I can't understand. Are you trying to let jimgui to use lwjgl's pointer, or let lwjgl to use jimgui's pointer?

**Comment by Jerem584** [comment] 2019-08-18 08:54
jimgui to use lwjgl's pointer

**Comment by ice1000** [comment] 2019-08-18 18:57
Duplicate of #18

**Closed by ice1000** 2019-08-18 18:57 UTC
Labels: duplicate
