### ISSUE TITLE
 Native library jimgui-glfw.dll not found.

### ISSUE THREAD

**Issue by kingdevnl** [ice1000/jimgui#33] opened 2019-06-05 08:37 UTC
So after iv'e called   JniLoaderEx.loadGlfw(); 
Then it's tossing this error:

`Exception in thread "main" java.lang.UnsupportedOperationException: Native library jimgui-glfw.dll not found.
	at org.ice1000.jimgui.util.NativeUtil.loadLibraryFromJar(NativeUtil.java:73)
	at org.ice1000.jimgui.util.JniLoaderEx.loadGlfw(JniLoaderEx.java:20)
	at com.kcraft.game.hud.HUD.init(HUD.java:79)
	at com.kcraft.game.KCraft.init(KCraft.java:103)
	at com.kcraft.engine.EngineMaster.start(EngineMaster.java:66)
	at com.kcraft.game.KCraft.main(KCraft.java:46)`

**Comment by ice1000** [comment] 2019-06-05 08:42
This is because I failed to compile the glfw+win32 version of the binding on my Windows machine when trying to build 0.8/0.8.1 version of jimgui.

You can rollback to 0.7 if it's necessary for you to use the glfw binding on Windows. Otherwise dx9 binding is preferred.

**Comment by ice1000** [comment] 2019-06-05 08:44
[jni.zip](https://github.com/ice1000/jimgui/files/3256286/jni.zip)

**Comment by kingdevnl** [comment] 2019-06-05 08:46
I'm working on a game in LWJGL, so kinda need to use my existing GLFW window Hahahah

**Comment by ice1000** [comment] 2019-06-05 09:33
Does 0.7 work for you?

**Comment by kingdevnl** [comment] 2019-06-05 09:40
Nope getting an JNI EXCEPTION_ACCESS_VIOLATION

**Comment by kingdevnl** [comment] 2019-06-05 09:42
Ok, so now it's not trowing that error but the entire screen turns into a blue ish color

**Comment by ice1000** [comment] 2019-06-05 09:57
This is what happened when I was trying to debug the glfw version on Windows. Will do more investigation

**Comment by ice1000** [comment] 2019-06-05 09:58
You can see I've struggled on this for long: #13 #18

**Comment by kingdevnl** [comment] 2019-06-05 10:03
Got discord for chat or something else?

**Comment by ice1000** [comment] 2019-06-05 10:18
See #34

**Comment by ice1000** [comment] 2019-06-11 21:44
Fixed in 0.9

**Comment by ice1000** [comment] 2019-06-11 21:45
For questions about `fromExistingPointer` or lwjgl-relevant stuffs, see #18

**Closed by ice1000** 2019-06-11 21:44 UTC
Labels: bug

**Comment by WindyOption** [comment] 2019-07-26 09:38
> Fixed in 0.9
In v0.9 , and my computer is win10x64
It throws "Got unsatisfied link error, please check the native library jimgui.dll"
and
jimgui.dll does exists in  C:\Users\{user}\AppData\Local\Temp\jimgui{TimeStamp}\jimgui.dll when i debug;

**Comment by ice1000** [comment] 2019-07-26 22:13
Dunno. How can I reproduce the error? Do you have a minimum reproducible example?
