### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by newk5** [ice1000/jimgui#66] opened 2020-12-13 01:45 UTC
I found memory leaks using the following functions:

- [ ] inputDouble
- [ ] inputFloat
- [ ] inputInt
- [ ] inputText
- [ ] pushID/popID

**Comment by ice1000** [comment] 2020-12-13 01:54
It'll be appreciated if you could post some snippets for testing and verification

**Comment by newk5** [comment] 2020-12-13 02:04
JniLoader.load();
     try (JImGui imgui = new JImGui()) {
         byte[] b = new byte[100];

         imgui.initBeforeMainLoop();
         while (!imgui.windowShouldClose()) {

                 imgui.initNewFrame();

                for (int i = 0; i < 50; i++) {

                     imgui.inputText("", b);
                }

                imgui.render();

         }
     }

You can change the code above to inputInt/Float/Double and the same issue will happen.

You can also add  imgui.pushID before creating the inputs and imgui.popID after to reproduce the leak with push/pop ID

**Comment by ice1000** [comment] 2020-12-13 06:53
Tbh, I don't see why they're leaking...

**Comment by ice1000** [comment] 2020-12-13 08:16
https://youtu.be/Yu04nU5rPO8

**Comment by newk5** [comment] 2020-12-13 21:44
After further tests I can conclude this is happening everywhere where String is used instead of JImStr

**Comment by ice1000** [comment] 2020-12-13 23:31
Then I'll consider this as a duplicate of #35

**Closed by ice1000** 2020-12-13 23:31 UTC

**Comment by newk5** [comment] 2020-12-13 23:37
Yea I guess this isn't a leak, it's just overhead from java strings being converted.
